# Generated by Django 4.0 on 2022-01-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.BooleanField(default=True),
        ),
    ]
