# Generated by Django 4.0 on 2022-02-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_message_read_message_text_unit_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
