# Generated by Django 4.0 on 2022-02-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='lease',
            field=models.FileField(blank=True, upload_to='leases/'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
