# Generated by Django 5.2.4 on 2025-07-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_user_profile_picture_alter_issue_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
