# Generated by Django 5.2.4 on 2025-07-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_issue_image_base64_message_image_base64_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='lease_base64',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
